//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT6_SkalochkinFedorISP321_PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CompleteOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPoint { get; set; }
        public Nullable<int> FIOClient { get; set; }
        public int CodeReceive { get; set; }
        public int OrderStatus { get; set; }
    
        public virtual CompleteOrder CompleteOrder1 { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual User User { get; set; }
    }
}
