//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT6_SkalochkinFedorISP321_PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID_Article { get; set; }
        public int ProductArticleNumber { get; set; }
        public int ProductName { get; set; }
        public string Unit { get; set; }
        public decimal ProductCost { get; set; }
        public int SizeMaxDiscount { get; set; }
        public int ProductManufacturer { get; set; }
        public int ProductSupplier { get; set; }
        public int ProductCategory { get; set; }
        public int ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Title Title { get; set; }
        public virtual TovarCategory TovarCategory { get; set; }
    }
}
